### PR TITLE
feat: add yuv support

### PR DESCRIPTION
**Pull request by wep21**
Signed-off-by: wep21 <border_goldenmarket@yahoo.co.jp>

### CODE REVIEW

**Comment by wep21** [comment]
@jbohren @clydemcqueen Could you review this PR? This PR supports yuv image encoding.

**Comment by clydemcqueen** [comment]
Nice improvement! Looks good to me.

I tested this on Foxy, Galactic and Rolling.

I noticed that the `image_encoding` parameter is missing from the README. (This is true for ROS1 as well.) Can you add it to the README and list the supported encodings?

Possible future work: it would be nice to have a set of tests that quickly run through the possible encodings and check for output.

**Comment by wep21** [comment]
@jbohren friendly ping

**Comment by wep21** [comment]
@clydemcqueen I added the parameter description at https://github.com/ros-drivers/gscam/pull/78/commits/e3fc18ccd068057383e9b459792283a7a667ee6b

**Comment by clydemcqueen** [comment]
@wep21 LGTM++

**Pull request merged**
